apiVersion: v1
kind: Service
metadata:
  name: party-b
spec:
  type: NodePort
  ports:
    - name: p2p
      port: 10002
      targetPort: 10002
    - name: rpc
      port: 10003
      targetPort: 10003
  selector:
    app: party-b
