#kind: ConfigMap
#metadata:
#name: postgresql-initdb-config
#data:
#init.sql: |
#  CREATE TABLE IF NOT EXISTS customers (
#      customer_id bpchar NOT NULL,
#      company_name character varying(40) NOT NULL,
#      contact_name character varying(30),
#      contact_title character varying(30),
#      address character varying(60),
#      city character varying(15),
#      region character varying(15),
#      postal_code character varying(10),
#      country character varying(15),
#      phone character varying(24),
#      fax character varying(24)
#  );
#
#  INSERT INTO customers VALUES ('ALFKI', 'Alfreds Futterkiste', 'Maria Anders', 'Sales Representative', 'Obere Str. 57', 'Berlin', NULL, '12209', 'Germany', '030-0074321', '030-0076545');
