kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-n1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/var/log/data/postgres/notary/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-n1
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-n1
spec:
  selector:
    matchLabels:
      app: postgres-n1
  template:
    metadata:
      labels:
        app: postgres-n1
    spec:
      #      volumes:
      #        - name: postgres-storage
      #          persistentVolumeClaim:
      #            claimName: postgres-pv-claim
      containers:
        - image: postgres
          name: postgres-n1
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-n1
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-n1
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-n1
                  key: postgres_db
          #            - name: PGDATA
          #              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres-n1
          volumeMounts:
            - name: postgres-persistent-storage-n1
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage-n1
          persistentVolumeClaim:
            claimName: postgres-pv-claim-n1
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-n1
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-n1
