#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgres-pv-claim
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 2Gi
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: postgresql-claim0
#labels:
#  type: local
#spec:
#  storageClassName: manual
#capacity:
#  storage: 1Gi
#accessModes:
#  - ReadWriteOnce
#hostPath:
#  path: "/home/feil_zou/corda4/volume/postgres/party-c/data"
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-c
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres/party-c/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-c
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-c
spec:
  selector:
    matchLabels:
      app: postgres-c
  template:
    metadata:
      labels:
        app: postgres-c
    spec:
      #      volumes:
      #        - name: postgres-storage
      #          persistentVolumeClaim:
      #            claimName: postgres-pv-claim
      containers:
        - image: postgres
          name: postgres-c
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-c
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-c
                  key: postgres_password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-c
                  key: postgres_db
          #            - name: PGDATA
          #              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres-c
          volumeMounts:
            - name: postgres-persistent-storage-c
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage-c
          persistentVolumeClaim:
            claimName: postgres-pv-claim-c
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-c
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres-c
